on:
  push:
    branches: main

name: pkgdown

jobs:
  pkgdown:
    uses: BristolMyersSquibb/blockr.ci/.github/workflows/pkgdown.yaml@main
    with:
      deploy: actions
    permissions:
      contents: read
      pages: write
      id-token: write
